services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports: 
      - "8080:8080"
    command: /bin/sh -c "while sleep 1000; do :; done"