services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    env_file: .env
    ports: 
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
  
volumes:
  node_modules: