services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DB_HOST=db
    ports: 
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - sontoco-network

  db:
    image: mariadb:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
      # bootstrap demo data
      - ./demodata/prod:/docker-entrypoint-initdb.d
    networks:
      - sontoco-network
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD

volumes:
  node_modules:
  database:

networks:
  sontoco-network:
    driver: bridge
