import { ApplicantEntityType, AssetType, InvestmentInstrument } from '@interfaces';
import Brand from '@brand/brandLabels';
import { StepName } from './application.store';

export default {
  LoadingApplication: 'We are loading your application',
  SigningIn: 'Attempting to sign you in',
  LoggedOut: 'You have been logged out of the application.',
  LoginApplication: `Please enter the email and PIN provided to you by your ${Brand.ShortName} representative.`,
  LoginFail: 'We could not find an application matching that information. Please check the information and try again',
  LoginError: 'The website experienced an error while trying to log you in. Please contact your representative.',
  PageTitle: `${Brand.ShortName} Client Application`,
  ApplicationTitle: 'Application',
  EnterEmail: 'Enter your email',
  EnterPIN: 'Enter your PIN',
  StartApplication: 'Start application',
  SavingChanges: 'Saving your changes',
  YouHaveErrorsTitle: 'Are you sure?',
  YouHaveErrorsMessage: 'There is a problem with some of the information you provided. You can return to this step to fix the information later. We will not be able to process your application until the information is fixed.',
  YouHaveErrorsAreYouSure: 'Are you sure you want to leave this step?',
  YouHaveErrorsStayHere: 'Stay here',
  YouHaveErrorsProceed: 'Go ahead',
  invalidFields: (count: number) => `Please fix the ${count === 1 ? 'error' : `${count} errors`} to continue.`,
  Next: 'Next',
  Back: 'Back',
  Step: 'step',
  StepOf: 'of',
  StepTitle: (stepName: StepName) => {
    const names: {[key in StepName]: string} = {
      [StepName.Disclaimer]: 'Disclaimer',
      [StepName.Information]: 'Information',
      [StepName.Experience]: 'Experience',
      [StepName.Targets]: 'Targets',
      [StepName.FinancialStatus]: 'Financial status',
      [StepName.Contact]: 'Contact info',
      [StepName.Fund]: 'Fund info',
      [StepName.Sign]: 'Complete and Sign',

    };
    return names[stepName];
  },
  Disclaimer: 'Disclaimer',
  DisclaimerInstruction: 'Please read this carefully',
  DisclaimerMessages: ['We know, it\'s boring, but its important 😊', 'Be sure to give it a good read 🧐', 'Thank you for bearing with us 😁'],
  DisclaimerAccept: 'I Understand',
  ClientInformation: 'Account Information',
  EntityInstruction: 'Please indicate the personhood of the entity on whose behalf this application is being completed.',
  NameInstruction: 'Please enter the full legal name of the entity for which the account will be opened',
  NameEntity: (enumVal: ApplicantEntityType) => `${ApplicantEntityType[enumVal]}'s full legal name`,
  CorpName: 'Entity legal name',
  Name: 'First name',
  LastName: 'Last name',
  DateOfBirthMonth: 'Month',
  DateOfBirthMonthPlaceholder: 'MM',
  DateOfBirthDay: 'Day',
  DateOfBirthDayPlaceholder: 'DD',
  DateOfBirthYear: 'Year',
  DateOfBirthYearPlaceholder: 'YYYY',
  IdentificationNumberInstruction: 'Please enter the identification number for the individual (such as a passport number)',
  IdentificationPlaceholder: 'ex: passport number',
  IdentificationNumber: 'Identification number',
  CountrySelect: 'Choose a country from the list',
  TaxCountry: 'Tax paying country',
  AddressInstruction: 'Please enter the full legal address of the applicant',
  AddressLine1: 'Address line 1',
  AddressLine2: 'Address line 2',
  AddressCity: 'City',
  AddressProvince: 'Province/State',
  AddressCountry: 'Country',
  AddressPostal: 'Postal code',
  Phone: 'Phone number (with country code, +1 for US)',
  Email: 'Email address',
  EducationLevel: 'Education level',
  Profession: 'Profession',
  InvestmentExperience: 'Experience and Knowledge',
  InvestmentExperienceInstruction: 'Please indicate the instruments you have previously invested in or have knowledge about.',
  InvestmentExperienceOtherInstruction: 'Please specify the other instruments you have experience with',
  InvestmentInstrumentDescription: {
    [InvestmentInstrument.Bonds]: 'Bonds',
    [InvestmentInstrument.Derivatives]: 'Derivatives',
    [InvestmentInstrument.FundInvestments]: 'Investment in funds',
    [InvestmentInstrument.HedgeFunds]: 'Hedge funds',
    [InvestmentInstrument.Independent]: 'Independent investing for 3+ years',
    [InvestmentInstrument.Investments]: 'Investments',
    [InvestmentInstrument.None]: 'None',
    [InvestmentInstrument.ShortTerm]: 'Short-term investments',
    [InvestmentInstrument.Stocks]: 'Stocks',
    [InvestmentInstrument.StructuredProducts]: 'Structured products',
    [InvestmentInstrument.Warrants]: 'Warrants',
    [InvestmentInstrument.WealthManagement]: 'Wealth management service',
    [InvestmentInstrument.Other]: 'Other',
  },
  AssetTypeDescription: {
    [AssetType.Alternative]: 'Alternative investments',
    [AssetType.BankInvestments]: 'Bank investments',
    [AssetType.Funds]: 'Funds',
    [AssetType.Other]: 'Other',
    [AssetType.RealEstate]: 'Real estate',
    [AssetType.Stocks]: 'Stocks',
  },
  InvestmentTargets: 'Investment Targets',
  InvestmentLengthInstruction: 'Please indicate your expected length of investment',
  InvestmentLength3Years: 'up to 3 years',
  InvestmentLength10Years: 'up to 10 years',
  InvestmentLengthMore: 'More than 10 years',
  InvestmentLengthOther: 'Other',
  InvestmentLengthYears: 'years',
  InvestmentLengthOtherInstruction: 'Please specify your expected length of investment',
  InvestmentRiskInstruction: 'Please indicate your desired risk profile',
  InvestmentRiskHigh: 'High risk. Best possible profit',
  InvestmentRiskAverage: 'Average risk, taking into consideration the market conditions. Good profit.',
  InvestmentRiskLow: 'Low risk. Moderate profit.',
  FinancialStatus: 'Financial Status',
  AuthorizedByEntityInstruction: 'As you are not applying as a private individual, please read and confirm the following by checking the box.',
  AuthorizedByEntityLabel: 'I hereby confirm that I am authorized to invest the company’s money and that the company is the ultimate beneficial owner.',
  IncomeSourceInstruction: 'Please indicate the source of income for the entity on whose behalf this application is being completed.',
  IncomeSourceActive: 'Active income (from employment, business ownership, etc.)',
  IncomeSourcePassive: 'Passive income (from investments, etc.)',
  IncomeSourceOther: 'Other',
  IncomeSourceOtherInstruction: 'Please specify the other income source',
  IncomeSize: 'Size of income (USD, net, monthly)',
  IncomeCommitmentsSize: 'Size of regular financial commitments (USD, monthly):',
  IncomeTotalAssetsSize: 'Total financial assets, approx. (USD)',
  IncomeTotalDebtsSize: 'Total debts and liabilities, approx. (USD)',
  AssetTypesInstruction: 'Please indicate the types of financial assets (USD)',
  AssetTypesOtherInstruction: 'Please specify the other asset types',
  ContactInformation: 'Contact Information',
  ContactInformationInstruction: 'Please provide the contact information for the person who is completing this application.',
  ContactInformationSubtitle: 'In case of foundation/corporation, the contact person is the representative of the foundation/corporation.',
  FundSummaryTitle: 'Fund Summary',
  FundSummarySubtitle: `${Brand.FullName} - ${Brand.FundName}`,
  FundSummaryParagraphs: Brand.FundSummaryParagraphs(),
  InvestorSuitabilityStandards: 'Investor Suitability Standards',
  ISSSubtitle: 'THE INVESTMENT IN A MANAGED FOREX TRADING ACCOUNT INVOLVES SIGNIFICANT RISKS AND IS NOT A SUITABLE INVESTMENT FOR ALL POTENTIAL INVESTORS.',
  ISS: [
    { intro: 'General:', paragraph: ['Investment in a Managed FOREX Trading Program involves significant risks and is suitable only for persons of adequate financial means who have no need for liquidity with respect to their investment and who can bear the economic risk of a complete loss of their investment. The suitability standards discussed below represent minimum suitability standards for prospective investors. The satisfaction of such standards by a prospective investor does not necessarily mean that the Managed FOREX Trading Program is a suitable investment for such prospective investor. Prospective investors are encouraged to consult their personal financial advisors to determine whether an investment in the Managed FOREX Trading Program is appropriate. We will require each investor to represent in writing that, among other things, (i) by reason of the investor’s business or financial experience, or that of the investor’s professional advisor, the investor is capable of evaluating the merits and risks of an investment in the Managed FOREX Trading Program and of protecting its own interests in connection with the transaction; (ii) the investor is investing for its own account and for investment only; (iii) such investor meets the suitability requirements set forth below.'] },
    { intro: 'Suitability Requirements:', paragraph: ['Each investor must represent in writing that it qualifies as an “accredited investor” as such term is defined in Rule 501(a) of Regulation D under the Securities Act, and must demonstrate the basis for such qualification. To be an accredited investor, an investor must fall within any of the following categories at the time of the investment into the Managed FOREX Trading Program by that investor:'], subsections: ['any bank as defined in Section 3(a)(2) of the Securities Act, or any savings and loan association or other institution as defined in Section 3(a)(5)(A) of the Securities Act whether acting in its individual or fiduciary capacity; any broker dealer registered pursuant to Section 15 of the Exchange Act, any insurance company as defined in Section 2(13) of the Securities Act; any investment company registered under the Investment Company Act of 1940 or a business development company as defined in Section 2(a)(48) of that Act; any Small Business Investment Company licensed by the U.S. Small Business Administration under Section 301(c) or (d) of the Small Business Investment Act of 1958; any plan established and maintained by a state, its political subdivisions, or any agency or instrumentality of a state or its political subdivisions, for the benefit of its employees, if such plan has total assets in excess of $5,000,000; any employee benefit plan within the meaning of the Employee Retirement Income Security Act of 1974 if the investment decision is made by a plan fiduciary, as defined in Section 3(21) of such Act, which is either a bank, savings and loan association, insurance company, or registered investment advisor, or if the employee benefit plan has total assets in excess of $5,000,000 or, if a self-directed plan, with investment decisions made solely by persons that are accredited investors;', 'any private business development company as defined in Section 202(a)(22) of the Investment Advisors Act of 1940;', 'any organization described in Section 501(c)(3) of the Internal Revenue Code, or any corporation, business trust or partnership not formed for the specific purpose of acquiring the securities offered, and that has total assets in excess of $5,000,000;', 'any director or executive officer of the Company;', 'any natural person whose individual net worth or joint net worth with that person’s spouse, at the time of investment in the Securities and excluding the value of your primary residence in making such determination, exceeds $1,000,000;', 'any natural person who had an individual income in excess of $200,000 in each of the two most recent years or joint income with that person’s spouse in excess of $300,000 in each of those years and has a reasonable expectation of reaching that same income level in the current year;', 'any trust, with total assets in excess of $5,000,000, not formed for the specific purpose of acquiring the Securities, whose purchase is directed by a sophisticated person as described in Rule 506(b)(2)(ii) of Regulation D; or', 'an entity in which all of the equity owners are accredited investors.'] }],
  ISS2: ['As used in this Investor Suitability Standards document, the term “net worth” means the excess of total assets, excluding the value of personal residences, over total liabilities. In determining income, an investor should add to his or her adjusted gross income any amounts attributable to tax-exempt income received, losses claimed as a limited partner in any limited partnership, deductions claimed for depreciation, contributions to an IRA or Keogh retirement plan, alimony payments and any amount by which from long-term capital gains has been reduced in arriving at adjusted gross income.', 'Prospective investors will be required to represent in writing that they meet the suitability standards set forth above, which represent minimum suitability requirements for prospective investors. Satisfaction of such standards by a prospective investor does not mean that the Securities are a suitable investment for such investor. In addition, certain states may impose additional or different suitability standards, which may be more restrictive.', 'The Company may make or cause to be made such further inquiry and obtain such additional information as it deems appropriate with regard to the suitability of prospective investors.', 'If any information furnished or representations made by a prospective investor or others acting on its behalf mislead the Company as to the suitability or other circumstances of such investor, or if, because of any error or misunderstanding as to such circumstances, a copy of this “Investor Suitability Standards” document is delivered to any such prospective investor.'],
  SignTitle: 'Finalize and Sign',
  SignInstruction: 'Please review the information you have provided in all steps before proceeding to finalize and electronically sign your application.',
  SignPretext: 'I hereby acknowledge and confirm:',
  SignAuthentic: `I have presented authentic and legitimate identification documents and provided accurate and truthful information on my identity, representative capacity, domicile, legal capacity, occupation, business purposes, and other required identifying information. Should any information provided herein change, I undertake to inform ${Brand.FullName} of the same within 5 days from the occurrence of the change.`,
  SignNotUnlawful: `I further declare that the funds I will invest in ${Brand.FullName} are not from any unlawful activities. This declaration survives this document and shall be deemed to cover all investments I may subsequently make.`,
  SignButtonLabel: 'Sign',
  SignLinkInstruction: 'Clicking the button below will finalize your application and take you to DocuSign where you will electronically sign your application.',
  ApplicationComplete: 'Thank you for completing the application. We will contact you soon after processing your application.',
};
