const Brand = {
  ShortName: 'Sontoco',
  MidName: 'Sontoco Holdings',
  FullName: 'Sontoco Holdings Corp.',
  PoweredBy: 'Sontoco Technologies',
  FundName: 'McGround Fund',
  AdminEmail: 'sontococcountshelp@sontocoholdings.com',
  StatementAddress: {
    street: '123 Main Street',
    city: 'Any City',
    state: 'Any Province',
    country: 'Any Country',
  },
  StatementMessage: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem. Placerat duis ultricies lacus sed turpis. Tincidunt ornare massa eget egestas purus viverra accumsan in nisl. Et ligula ullamcorper malesuada proin libero. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Volutpat sed cras ornare arcu dui vivamus arcu. Imperdiet proin fermentum leo vel orci porta. Lacus sed turpis tincidunt id aliquet risus feugiat. Duis at tellus at urna. Orci ac auctor augue mauris augue neque gravida in fermentum. Ornare aenean euismod elementum nisi. Imperdiet sed euismod nisi porta lorem mollis. Congue nisi vitae suscipit tellus. Viverra vitae congue eu consequat ac felis donec et.',
  FundSummaryParagraphs() {
    return [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suspendisse faucibus interdum posuere lorem. Placerat duis ultricies lacus sed turpis. Tincidunt ornare massa eget egestas purus viverra accumsan in nisl. Et ligula ullamcorper malesuada proin libero. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Volutpat sed cras ornare arcu dui vivamus arcu. Imperdiet proin fermentum leo vel orci porta. Lacus sed turpis tincidunt id aliquet risus feugiat. Duis at tellus at urna. Orci ac auctor augue mauris augue neque gravida in fermentum. Ornare aenean euismod elementum nisi. Imperdiet sed euismod nisi porta lorem mollis. Congue nisi vitae suscipit tellus. Viverra vitae congue eu consequat ac felis donec et.',
      'Magna fermentum iaculis eu non. Consectetur libero id faucibus nisl tincidunt eget nullam non. Pharetra massa massa ultricies mi. Tellus elementum sagittis vitae et. Ut porttitor leo a diam. Pellentesque sit amet porttitor eget dolor morbi. Non odio euismod lacinia at. Sagittis aliquam malesuada bibendum arcu. Rutrum tellus pellentesque eu tincidunt. Semper quis lectus nulla at volutpat diam ut. Tempor orci dapibus ultrices in iaculis. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Consectetur adipiscing elit duis tristique sollicitudin nibh sit. Posuere urna nec tincidunt praesent semper feugiat nibh sed pulvinar.',
      'Tellus pellentesque eu tincidunt tortor aliquam nulla. Egestas sed sed risus pretium. Consequat nisl vel pretium lectus. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in. Habitasse platea dictumst vestibulum rhoncus. Consequat semper viverra nam libero justo laoreet sit amet. Pharetra et ultrices neque ornare aenean. Morbi tincidunt augue interdum velit euismod. Elementum nisi quis eleifend quam adipiscing vitae. Rhoncus urna neque viverra justo nec ultrices dui. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Amet aliquam id diam maecenas ultricies mi eget. Etiam tempor orci eu lobortis elementum nibh tellus molestie. Bibendum est ultricies integer quis. In ornare quam viverra orci sagittis. Turpis in eu mi bibendum neque egestas congue quisque. Et leo duis ut diam quam nulla porttitor massa id.',
      'Sed vulputate odio ut enim blandit volutpat maecenas. Pulvinar pellentesque habitant morbi tristique senectus et netus. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Vivamus at augue eget arcu dictum varius duis at consectetur. Interdum posuere lorem ipsum dolor sit amet consectetur. Sit amet justo donec enim. Gravida neque convallis a cras semper auctor neque. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Maecenas accumsan lacus vel facilisis volutpat est. Sagittis id consectetur purus ut faucibus pulvinar elementum. Sit amet consectetur adipiscing elit ut aliquam purus. Tortor id aliquet lectus proin. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum.',
      'Et sollicitudin ac orci phasellus. Morbi blandit cursus risus at ultrices mi tempus imperdiet. Aliquam faucibus purus in massa. Enim ut sem viverra aliquet eget sit. Aliquet nibh praesent tristique magna sit amet. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Libero justo laoreet sit amet cursus. Diam in arcu cursus euismod quis viverra nibh cras. Habitant morbi tristique senectus et netus et malesuada fames ac. Libero justo laoreet sit amet cursus sit. Libero id faucibus nisl tincidunt eget nullam non nisi est. Praesent semper feugiat nibh sed pulvinar proin gravida. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Elementum pulvinar etiam non quam lacus suspendisse. Nisl nunc mi ipsum faucibus vitae. A erat nam at lectus. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Lectus urna duis convallis convallis tellus id interdum velit laoreet.',
      'Massa sapien faucibus et molestie ac feugiat sed lectus. Maecenas pharetra convallis posuere morbi leo urna molestie. Curabitur vitae nunc sed velit dignissim sodales ut. A diam sollicitudin tempor id. Ante in nibh mauris cursus. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Eleifend donec pretium vulputate sapien nec sagittis. Nisi est sit amet facilisis magna etiam tempor. Sapien nec sagittis aliquam malesuada.',
      'Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Placerat in egestas erat imperdiet sed euismod nisi. Id volutpat lacus laoreet non curabitur gravida. Tristique magna sit amet purus gravida quis blandit. Eget aliquet nibh praesent tristique magna sit. Aliquam sem fringilla ut morbi tincidunt augue. Mattis aliquam faucibus purus in. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Ultricies mi quis hendrerit dolor magna eget est lorem. Lobortis feugiat vivamus at augue eget arcu dictum.',
      'Eget nunc scelerisque viverra mauris in aliquam sem fringilla ut. Turpis egestas pretium aenean pharetra magna ac placerat. Eget nunc lobortis mattis aliquam faucibus purus. Erat nam at lectus urna duis convallis convallis. Vel turpis nunc eget lorem dolor sed. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Egestas integer eget aliquet nibh praesent tristique. Ac placerat vestibulum lectus mauris ultrices eros in cursus turpis. Facilisis sed odio morbi quis commodo odio aenean sed adipiscing. Vel pharetra vel turpis nunc.',
    ];
  },
};

export default Brand;
